### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by omarsumadi** [slicefox/django-gsuite-email#1]
Hi,

Just wanted to clarify some documentation - we create a service account credential file - okay. How do we tell your awesome repo to use that?

Surely we can't just set the email backend and from email - there must be more?

Thanks for all your hard work slicefox!
Omar

**Comment by slicefox** [comment]
Hi Omar,

Don't know how it slipped my mind, Thank you for pointing it out, I have now added the missing step in README.
