### ISSUE TITLE
dependency mismatch with other google installs gspread, google-cloud-tasks

### ISSUE THREAD

**Issue by quteharry19** [slicefox/django-gsuite-email#2]
![image](https://user-images.githubusercontent.com/44421422/123037277-02680680-d40c-11eb-9399-2d22652c149f.png)

**Comment by slicefox** [comment]
Hi, Thanks for bringing this up.
I have removed the hard dependency, this is fixed in v0.1.2 release.

**Comment by quteharry19** [comment]
Great
